# Change these first
owner: valassis-fcalle # Your GitHub organization or username, where this repository lives
repo: savi-uptime # The name of this repository

sites:
  - name: OfferManager
    url: https://coupons.valassis.eu/lib/offermanager/latest/init.html?mapped=/capi/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: 🇩🇪 Savi Deutschland
    url: https://savigermany.de/
  - name: 🇪🇸 Savi Spain
    url: https://www.valesycupones.es/
  - name: 🇮🇹 Savi Italy
    url: https://saviitalia.it/
  - name: 🇬🇧 Savi UK
    url: https://saviuk.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /savi-uptime
  logoUrl: https://avatars.githubusercontent.com/u/928559?s=200&v=4
  name: Savi Sites Uptime
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: © Savi 2022
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
